name: CI
on: [push, pull_request]
jobs:
  container-job:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:1.18.2
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18.2
      id: go

    - name: Check out source
      uses: actions/checkout@v1

    - name: Run Go Vet
      run: go vet -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
    
    - name: Run Go Tests
      run: POSTGRES_CONNECTION=postgres://postgres:password@postgres:5432/postgres go test ./... -v -cover -covermode=count -coverprofile=coverage.out 
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
